### PR TITLE
Avoid direct use of `MakeCredentialsOptions` and `GetAssertionOptions` in the public API

### LINKED ISSUE #255: examples/ctap2.rs panics with UnsupportedOption on some devices
When I [apply a patch to fix clone_device_as_write_only](https://github.com/mozilla/authenticator-rs/issues/252), and run examples/ctap2.rs with a Yubikey 5 Nano, it immediately crashes with an UnsupportedOption panic before I even have an opportunity to interact with the device:

```
[2023-04-21T11:01:03Z DEBUG authenticator::ctap2::commands::make_credentials] Serialize MakeCredentials
STATUS: Continuing with device: Vendor: Unknown Vendor, Device: Unknown Device, Interface: 2, Firmware: v5.2.4, Capabilities: 05
[2023-04-21T11:01:03Z DEBUG authenticator::transport] got from Device "/dev/uhid0" status=Cbor: [43]
[2023-04-21T11:01:03Z DEBUG authenticator::ctap2::commands::make_credentials] response status code: UnsupportedOption
[2023-04-21T11:01:03Z WARN  authenticator::statemachine] error happened: Error: Error issuing command: CommandError: Unexpected code: UnsupportedOption (None)
thread '[2023-04-21T11:01:03Z DEBUG authenticator::authenticatorservice] Callback observer is running, cancelling 0 unchosen transports...
main' panicked at 'Registration failed: HIDError(Command(StatusCode(UnsupportedOption, None)))', examples/ctap2.rs:222:23
```

[ctap2.log](https://github.com/mozilla/authenticator-rs/files/11295119/ctap2.log)

I tried a patch to stop serializing the options in MakeCredentials::serialize, and after that it worked.  I tried with and without the attached [option.patch](https://github.com/mozilla/authenticator-rs/files/11296248/option.patch), and with and without the `--fallback` flag in https://github.com/mozilla/authenticator-rs/pull/253, with the following results:

| device                | none  | fb    | patch | patch+fb      | caps |
| --------------------- | ----- | ----- | ----- | ------------- | ---- |
| Yubikey 5C Nano       | +     | +     | +     | +             | 05   |
| Yubikey 5 Nano        | -     | +     | +     | +             | 05   |
| Yubico Seckey NFC     | -     | +     | +     | +             | 05   |
| Yubikey 4             | +     | +     | +     | +             | 01   |
| SoloKeys Somu         | +     | +     | +     | +             | 05   |

The main issue is that it seems the [TODO comment left early last year](https://github.com/mozilla/authenticator-rs/blob/28e3931530ed2174953e2b84916ffc442067227f/src/ctap2/commands/make_credentials.rs#L117-L120) indicates an actual compatibility problem with several widely used devices on the market.

Two side questions:

1. Is there a way to dump the transaction messages like in libfido2 with FIDO_DEBUG=1?  It would be helpful to see exactly what the device objects to (and it would be really nice to able to replay it with tweaks, but I realize that's a tall order).
2. Does the ctap2 example display somewhere which paths (CTAP1, CTAP2.0, CTAP2.1) are being used for the transaction?

### PR DESCRIPTION
**Pull request by jschanck**
We were previously using the `user_verification` field in `MakeCredentialsOptions` and `GetAssertionOptions` to
1) encode the WebAuthn user verification requirement in the public API, and
2) encode the uv option in CTAP commands.

This was prone to bugs, e.g. #255.

This PR removes the `MakeCredentialsOptions` and `GetAssertionOptions` structs from the public API.

The "Improve handling of" patch also implements some checks from step 2 of Sections [10.2](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#u2f-authenticatorMakeCredential-interoperability) and [10.3](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#u2f-authenticatorGetAssertion-interoperability) of CTAP 2.1 that we were missing.

Resolves #255

### CODE REVIEW

File: src/statemachine.rs [hunk 1]
```diff
@@ -232,8 +254,12 @@ impl StateMachine {
                     PinUvAuthResult::SuccessGetPinUvAuthTokenUsingUvWithPermissions,
                     pin_auth_token,
                 )
-            } else if supports_pin && pin_configured {
+            } else {
                 // CTAP 2.1 - PIN
+                // We would have exited earlier if !pin_configured && !supports_uv,
+                // So we have pin_configured || (skip_uv && supports_uv)
+                // TODO(https://github.com/mozilla/authenticator-rs/issues/223)
+                // It should not be possible to arrive here in the !pin_configured case.
```
Comment (msirringhaus) [inline src/statemachine.rs]: I don't think this comment is true? 
Suppose, there is no PIN configured, but the token supports UV. And we skip UV. Then we will end up here.
The early exit does not take `skip_uv` into account.

File: src/statemachine.rs [hunk 2]
```diff
@@ -613,27 +672,61 @@ impl StateMachine {
...
+                    // GetAssertion::RequestCtap1
+                    if args.user_verification_req == UserVerificationRequirement::Required {
+                        callback.call(Err(AuthenticatorError::UnsupportedOption(
+                            UnsupportedOption::UserVerification,
+                        )));
+                        return;
+                    }
+                    if args.allow_list.is_empty() {
+                        callback.call(Err(AuthenticatorError::UnsupportedOption(
+                            UnsupportedOption::AllowList,
```
Comment (msirringhaus) [inline src/statemachine.rs]: Maybe call the error `UnsupportedOption::EmptyAllowList`? Otherwise it sounds like having an allow list is unsupported, which may be confusing, when this error is printed somewhere.

File: src/statemachine.rs (hunk 1 above)
Comment (jschanck) [reply src/statemachine.rs]: Yes, you're right.

File: src/statemachine.rs (hunk 2 above)
Comment (jschanck) [reply src/statemachine.rs]: Sounds good.

File: src/statemachine.rs [hunk 3]
```diff
@@ -613,27 +678,61 @@ impl StateMachine {
...
-                    if let Some(auth) = dev.get_authenticator_info() {
-                        if !auth.supports_hmac_secret() {
-                            callback.call(Err(AuthenticatorError::UnsupportedOption(
-                                UnsupportedOption::HmacSecret,
-                            )));
-                            return;
-                        }
+
+                // We need a copy of the arguments for this device
+                let args = args.clone();
```
Comment (mozkeeler) [inline src/statemachine.rs:691]: This doesn't seem necessary - can't `args` be moved into this closure?

File: src/statemachine.rs [hunk 4]
```diff
@@ -613,27 +678,61 @@ impl StateMachine {
...
+                    }
+                    if args.allow_list.is_empty() {
+                        callback.call(Err(AuthenticatorError::UnsupportedOption(
+                            UnsupportedOption::EmptyAllowList,
+                        )));
+                        return;
                     }
                 }
+
+                let mut getassertion = GetAssertion::new(
```
Comment (mozkeeler) [inline src/statemachine.rs]: nit: maybe `get_assertion`?

**Review by mozkeeler — APPROVED** [review]
LGTM!

File: src/statemachine.rs [hunk 5]
```diff
@@ -213,16 +236,21 @@ impl StateMachine {
...
         // are allowing for 'discouraged', meaning no auth required.
-        if cmd.can_skip_user_verification(info) {
+        if cmd.can_skip_user_verification(info, uv_req) {
             return Ok(PinUvAuthResult::NoAuthRequired);
         }
 
         // Device does not support any auth-method
-        if !pin_configured && !supports_uv {
-            // We'll send it to the device anyways, and let it error out (or magically work)
+        if (skip_uv || !supports_uv) && !supports_pin {
```
Comment (jschanck) [inline src/statemachine.rs:244]: @msirringhaus Can you think about whether we need to call `cmd.set_uv_option(Some(true))` here in the uv required case? And if so, what if `!supports_uv`. Do we need to error-out then?

File: src/statemachine.rs [hunk 6]
```diff
@@ -213,16 +236,21 @@ impl StateMachine {
...
             return Ok(PinUvAuthResult::NoAuthTypeSupported);
         }
 
+        // Device supports PINs, but a PIN is not configured. Signal that we
+        // can complete the operation if the user sets a PIN first.
+        if (skip_uv || !supports_uv) && !pin_configured {
+            return Err(AuthenticatorError::PinError(PinError::PinNotSet));
```
Comment (jschanck) [inline src/statemachine.rs:260]: I'm also not 100% certain of this. We might not want to use the PinNotSet error code here. We might want one specific to this case.

Comment (msirringhaus) [reply src/statemachine.rs:260]: I don't really see it used anywhere else or for anything else, so I'm not sure this is a problem. But since this is `PinError` and not `CommandError::StatusCode`, we can easily add another variant for this. Fine with me either way.

File: src/statemachine.rs (hunk 5 above)
Comment (msirringhaus) [reply src/statemachine.rs:244]: Hm, tricky. 

I'd say, if `supports_uv=true`, set the option. The device should then error out with `UvBlocked` or the like. As for PINs, Firefox should have popups to inform the user about that.

If `supports_uv=false`, we have two options:
* If we do NOT set it, then there is a good chance, the request succeeds, but the response will have `uv=false`. Some servers may still accept that (wrongly), and would mean less friction for the user. If the server does not accept it, it will error out (with a server-side error message). 
* If we DO set it, the device will very likely error out with `InvalidOption` or the like.

In principle, I'd favor setting it, and let  the device error out how it sees fit. The problem may here be: how do we inform the user about it in a sensible way? But that is a 'Firefox-side problem' so to speak. I think for the library, it should probably let the device error out.

Comment (jschanck) [reply src/statemachine.rs:244]: I agree with setting it in the `supports_uv=true` case. Looking a little closer at the spec ([makeCred 11.2](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#op-makecred-step-protected) and [getAssertion 6.2](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#sctn-getAssert-authnr-alg)), a conformant authenticator that supports uv should return `CTAP2_ERR_PIN_BLOCKED` if the uv retry counter is 0, which is the likely case when `supports_uv = true` and `skip_uv`. We show a device blocked notificaiton in Firefox when that happens.

I think, long term, we should probably work around the bugs in CTAP 2.0 devices which required the CTAP 2.1 spec to say "platforms MUST NOT include the uv option key if the authenticator does not support built-in user verification". I.e. we should handle the `InvalidOption` gracefully. But for now we should abide by the MUST NOT and let the server reject the response.

File: src/statemachine.rs (hunk 6 above)
Comment (jschanck) [reply src/statemachine.rs:260]: Yeah this seems to be the only place where we could create the associated `StatusUpdate`, so I'm going to leave it.

File: src/statemachine.rs (hunk 3 above)
Comment (jschanck) [reply src/statemachine.rs:691]: This was existing behavior, although I did change the comment. With the current design, each device calls the closure, so we need it to be `FnMut`.
