### PR TITLE
Remove HIDDevice::clone_device_as_write_only

### LINKED ISSUE #252: Cloning devices does not work on several operating systems
On NetBSD, OpenBSD, probably FreeBSD, and I would guess most Unix systems, each device node for a HID can only be opened once at a time; subsequent attempts fail with EBUSY until the device is closed, so that separate programs can't just stomp over each other's input and output streams.  So the clone_device_as_write_only implementations on these systems which just reopen the same device path have never worked.

The symptom is that examples/ctap2.rs goes into a loop trying and failing to open any FIDO device, with cryptic log messages like this:

```
[2023-04-20T21:09:52Z WARN  authenticator::statemachine] error while cloning device: "/dev/uhid0"
[2023-04-20T21:09:52Z DEBUG authenticator::transport::device_selector] Device not a token event: "/dev/uhid0"
```

I tried the attached [clone.patch](https://github.com/mozilla/authenticator-rs/files/11290497/clone.patch) to make clone_device_as_write_only to dup the existing file descriptor -- this just gives a new descriptor number to refer to the same open state, in the hope that that's enough for authenticator-rs's purposes, although I got lost in the abstractions trying to figure out what these purposes are.  This seems to make more progress and identifies the device, but then crashes in a panic about UnsupportedOption ([ctap2.log](https://github.com/mozilla/authenticator-rs/files/11290512/ctap2.log)).

I tried using the main and ctap1 examples, but they're not there any more.  Is there a reduced test case that can just exercise the old reliable U2F protocol and none of the fragile bells and whistles of CTAP2 to make progress on this separately from fixing whatever is wrong with CTAP2?

### PR DESCRIPTION
**Pull request by jschanck**
riastradh observed in #252 that `HIDDevice::clone_device_as_write_only` is not implemented correctly on several operating systems. Due to the changes in 7e9cad878bcd03c3f4943372e236520a8edcf158, there's actually no need to write to the `Device` produced by `HIDDevice::clone_device_as_write_only`. However, the device metadata is still used by `DeviceSelector` to send status updates.

This PR removes `HIDDevice::clone_device_as_write_only` and makes `StateMachine` responsible for sending status updates that contain device metadata.

Resolves #252

### CODE REVIEW

File: src/statemachine.rs [hunk 1]
```diff
@@ -151,16 +151,27 @@ impl StateMachine {
...
+                    status,
+                    crate::StatusUpdate::DeviceSelected(dev.get_device_info()),
+                );
             }
             Err(_) => {
                 warn!("Error when trying to receive messages from DeviceSelector! Exiting.");
                 return None;
             }
         }
+        send_status(status, crate::StatusUpdate::SelectDeviceNotice);
```
Comment (jschanck) [inline src/statemachine.rs]: Hm, this causes Firefox's "Multiple devices available" prompt to be shown even when only one device is available. I'll attach another patch.

**Review by mozkeeler — APPROVED** [review]
SGTM!
